# Generated by Django 3.0.8 on 2021-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='bool_deleted',
            field=models.BooleanField(default=False, verbose_name='IS DELETED?'),
        ),
        migrations.AddField(
            model_name='meetourteem',
            name='bool_deleted',
            field=models.BooleanField(default=False, verbose_name='IS DELETED?'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='bool_deleted',
            field=models.BooleanField(default=False, verbose_name='IS DELETED?'),
        ),
    ]
