# Generated by Django 3.0.8 on 2021-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210408_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherservice',
            name='bool_deleted',
        ),
        migrations.RemoveField(
            model_name='otherservice',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='otherservice',
            name='title',
        ),
        migrations.AddField(
            model_name='otherservice',
            name='images',
            field=models.ImageField(default='mpoyi.jpg', upload_to='images/', verbose_name='IMAGE'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='name',
            field=models.CharField(default='name', max_length=250, verbose_name='NAME'),
        ),
    ]
